server:
  port: 9090
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: c##cpi
    password: c##cpi
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
